export const products = [
  // --------------------- SHOES (1–10) ---------------------
  {
    name: "AirFlex Running Shoes",
    description: "Lightweight running shoes with breathable mesh and shock-absorbing sole.",
    price: 89.99,
    stock: 10,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.6,
    isDeleted: false,
  },
  {
    name: "TrailGrip Outdoor Sneakers",
    description: "Durable sneakers designed for hiking and tough terrain support.",
    price: 74.5,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1600181954479-27b7c83a93a7?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  },
  {
    name: "UrbanWalk Casual Shoes",
    description: "Comfortable casual shoes suited for all-day walking.",
    price: 59.99,
    stock: 8,
    images: ["https://images.unsplash.com/photo-1584735175315-9d5df2271d9d?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 3.9,
    isDeleted: false,
  },
  {
    name: "ProRunner Max",
    description: "Professional running shoes with cushioned midsole.",
    price: 99.99,
    stock: 5,
    images: ["https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: true,
    ratings: 4.8,
    isDeleted: false,
  },
  {
    name: "FlexiSprint Athletic Shoes",
    description: "Performance sneakers for gym and sprint training.",
    price: 67.25,
    stock: 7,
    images: ["https://images.unsplash.com/photo-1528701800489-20be9f2b7d5f?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.4,
    isDeleted: false,
  },
  {
    name: "ComfortWalk Slip-ons",
    description: "Soft slip-on shoes with ergonomic cushioning.",
    price: 54.99,
    stock: 9,
    images: ["https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 3.7,
    isDeleted: false,
  },
  {
    name: "StreetVibe Sneakers",
    description: "Trendy streetwear sneakers designed for everyday fashion.",
    price: 79.49,
    stock: 6,
    images: ["https://images.unsplash.com/photo-1589395595558-c47a60d2aacb?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.1,
    isDeleted: false,
  },
  {
    name: "Matrix Sports Shoes",
    description: "Sports shoes offering strong grip and comfort.",
    price: 94.89,
    stock: 4,
    images: ["https://images.unsplash.com/photo-1588361861056-25e8e3d2e8fa?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.5,
    isDeleted: false,
  },
  {
    name: "FlashRun Pro",
    description: "Premium marathon shoes for long-distance running.",
    price: 101.5,
    stock: 3,
    images: ["https://images.unsplash.com/photo-1595341888016-a392ef81b7de?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: true,
    ratings: 4.7,
    isDeleted: false,
  },
  {
    name: "DailyStride Shoes",
    description: "Soft inner cushioning ideal for daily commutes.",
    price: 62.75,
    stock: 10,
    images: ["https://images.unsplash.com/photo-1561808843-dcdf40d6ebf8?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 3.8,
    isDeleted: false,
  },

  // --------------------- MEN'S CLOTHING (11–20) ---------------------
  {
    name: "Classic Cotton Shirt",
    description: "Comfortable cotton shirt suitable for office wear.",
    price: 35.99,
    stock: 15,
    images: ["https://images.unsplash.com/photo-1520975698519-59c2fdbc1bbf?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 4.3,
    isDeleted: false,
  },
  {
    name: "Denim Jeans",
    description: "Dark blue stretchable denim jeans.",
    price: 49.5,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 4.0,
    isDeleted: false,
  },
  {
    name: "Graphic T-Shirt",
    description: "Soft printed T-shirt with modern designs.",
    price: 22.75,
    stock: 20,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 3.9,
    isDeleted: false,
  },
  {
    name: "Formal Blazer",
    description: "Premium slim-fit blazer suitable for meetings and events.",
    price: 79.9,
    stock: 5,
    images: ["https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: true,
    ratings: 4.5,
    isDeleted: false,
  },
  {
    name: "Hooded Sweatshirt",
    description: "Warm and stylish hoodie for winter wear.",
    price: 42.99,
    stock: 8,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 4.1,
    isDeleted: false,
  },
  {
    name: "Slim-Fit Trousers",
    description: "Elegant trousers ideal for office and formal occasions.",
    price: 38.49,
    stock: 10,
    images: ["https://images.unsplash.com/photo-1598032895307-cd6e976a8f39?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  },
  {
    name: "Sports Tracksuit",
    description: "Breathable tracksuit for workouts and training.",
    price: 65.99,
    stock: 7,
    images: ["https://images.unsplash.com/photo-1521572160150-71a61e6f5ae8?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 4.6,
    isDeleted: false,
  },
  {
    name: "Casual Polo Shirt",
    description: "Premium polo T-shirt with soft cotton material.",
    price: 28.9,
    stock: 15,
    images: ["https://images.unsplash.com/photo-1530845641309-41c4b31c4fcf?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 4.0,
    isDeleted: false,
  },
  {
    name: "Winter Jacket",
    description: "Thick padded jacket for extremely cold weather.",
    price: 99.25,
    stock: 4,
    images: ["https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: true,
    ratings: 4.7,
    isDeleted: false,
  },
  {
    name: "Casual Shorts",
    description: "Lightweight cotton shorts for daily comfort.",
    price: 24.75,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1618354691643-cad54a4d65c7?auto=format&fit=crop&w=600&q=60"],
    category: "mens_clothing",
    featured: false,
    ratings: 3.8,
    isDeleted: false,
  },

  // --------------------- WOMEN'S CLOTHING (21–30) ---------------------
  {
    name: "Floral Summer Dress",
    description: "Lightweight floral dress ideal for summer outings.",
    price: 45.99,
    stock: 8,
    images: ["https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=60"],
    category: "womens_clothing",
    featured: false,
    ratings: 4.5,
    isDeleted: false,
  },
  {
    name: "Women’s Blue Denim Jacket",
    description: "Stylish denim jacket made with durable material.",
    price: 58.6,
    stock: 7,
    images: ["https://images.unsplash.com/photo-1536300354171-0c2df08b0095?auto=format&fit=crop&w=600&q=60"],
    category: "womens_clothing",
    featured: false,
    ratings: 4.4,
    isDeleted: false,
  },
  {
    name: "Soft Knit Sweater",
    description: "Warm knit sweater with a cozy texture.",
    price: 39.4,
    stock: 10,
    images: ["https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=60"],
    category: "womens_clothing",
    featured: false,
    ratings: 3.9,
    isDeleted: false,
  },
  {
    name: "Elegant Party Gown",
    description: "Premium party gown for weddings and special events.",
    price: 89.99,
    stock: 4,
    images: ["https://images.unsplash.com/photo-1520975920429-bd17f25beffd?auto=format&fit=crop&w=600&q=60"],
    category: "womens_clothing",
    featured: true,
    ratings: 4.8,
    isDeleted: false,
  },
  {
    name: "Casual Cotton Kurti",
    description: "Traditional kurti made from soft breathable cotton.",
    price: 22.1,
    stock: 15,
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2fd432?auto=format&fit=crop&w=600&q=60"],
    category: "womens_clothing",
    featured: false,
    ratings: 4.0,
    isDeleted: false,
  },
  {
    name: "Women’s Joggers",
    description: "Comfortable joggers perfect for workouts or travel.",
    price: 27.6,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=600&q=60"],
    category: "womens_clothing",
    featured: false,
    ratings: 3.8,
    isDeleted: false,
  },
    // --------------------- ELECTRONICS (31–40) ---------------------
  {
    name: "Wireless Bluetooth Headphones",
    description: "High-quality sound with noise-cancellation feature.",
    price: 59.99,
    stock: 15,
    images: ["https://images.unsplash.com/photo-1580894894512-8c6b7e4f93b0?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: true,
    ratings: 4.6,
    isDeleted: false,
  },
  {
    name: "Smart LED TV 42 Inch",
    description: "Full HD smart television with multiple HDMI ports.",
    price: 399.99,
    stock: 5,
    images: ["https://images.unsplash.com/photo-1606813909727-5a21ec02d6e2?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: true,
    ratings: 4.8,
    isDeleted: false,
  },
  {
    name: "Portable Power Bank 10000mAh",
    description: "Compact power bank with fast charging support.",
    price: 25.99,
    stock: 20,
    images: ["https://images.unsplash.com/photo-1562241749-ef6bfa6f3301?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  },
  {
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with long battery life.",
    price: 15.49,
    stock: 25,
    images: ["https://images.unsplash.com/photo-1587825140408-8df3e3428963?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: false,
    ratings: 4.1,
    isDeleted: false,
  },
  {
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit mechanical keyboard with tactile keys.",
    price: 79.99,
    stock: 10,
    images: ["https://images.unsplash.com/photo-1581090700227-4ab36f1197b7?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: true,
    ratings: 4.7,
    isDeleted: false,
  },
  {
    name: "Smartphone 128GB",
    description: "Latest smartphone with high-resolution camera.",
    price: 499.99,
    stock: 7,
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: true,
    ratings: 4.8,
    isDeleted: false,
  },
  {
    name: "Wireless Earbuds",
    description: "Compact earbuds with superior sound quality.",
    price: 29.99,
    stock: 18,
    images: ["https://images.unsplash.com/photo-1596894700637-ec6e6129c5df?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: false,
    ratings: 4.3,
    isDeleted: false,
  },
  {
    name: "4K Action Camera",
    description: "Waterproof action camera with wide-angle lens.",
    price: 149.99,
    stock: 6,
    images: ["https://images.unsplash.com/photo-1581276879432-15ffb1dca342?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: true,
    ratings: 4.5,
    isDeleted: false,
  },
  {
    name: "Laptop Backpack",
    description: "Durable backpack with padded laptop compartment.",
    price: 39.99,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  },
  {
    name: "Smartwatch Fitness Tracker",
    description: "Track your fitness, sleep, and notifications.",
    price: 89.49,
    stock: 9,
    images: ["https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=600&q=60"],
    category: "electronics",
    featured: true,
    ratings: 4.6,
    isDeleted: false,
  },

  // --------------------- ACCESSORIES (41–50) ---------------------
  {
    name: "Leather Wallet",
    description: "Premium genuine leather wallet with multiple slots.",
    price: 29.99,
    stock: 15,
    images: ["https://images.unsplash.com/photo-1593032465177-fcb53b83bfa0?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  },
  {
    name: "Sunglasses UV Protection",
    description: "Stylish sunglasses with full UV protection.",
    price: 19.99,
    stock: 20,
    images: ["https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.0,
    isDeleted: false,
  },
  {
    name: "Analog Wristwatch",
    description: "Classic watch with leather strap and metallic case.",
    price: 49.99,
    stock: 8,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.5,
    isDeleted: false,
  },
  {
    name: "Travel Luggage Set",
    description: "Durable luggage set with multiple compartments.",
    price: 129.99,
    stock: 6,
    images: ["https://images.unsplash.com/photo-1573883430500-9be7f2ad8d2e?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: true,
    ratings: 4.7,
    isDeleted: false,
  },
  {
    name: "Key Organizer",
    description: "Compact key organizer to prevent key jingle and scratches.",
    price: 14.49,
    stock: 25,
    images: ["https://images.unsplash.com/photo-1566013608983-0bba88c77f06?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.1,
    isDeleted: false,
  },
  {
    name: "Leather Belt",
    description: "High-quality leather belt for men and women.",
    price: 24.99,
    stock: 18,
    images: ["https://images.unsplash.com/photo-1591012905082-3d80c9f4f25f?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.3,
    isDeleted: false,
  },
  {
    name: "Beanie Cap",
    description: "Warm knitted beanie suitable for winter.",
    price: 12.99,
    stock: 20,
    images: ["https://images.unsplash.com/photo-1606813909727-5a21ec02d6e2?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 3.9,
    isDeleted: false,
  },
  {
    name: "Scarf Wool Blend",
    description: "Soft wool blend scarf for cold weather.",
    price: 18.49,
    stock: 15,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.1,
    isDeleted: false,
  },
  {
    name: "Travel Toiletry Bag",
    description: "Compact toiletry bag for travel essentials.",
    price: 22.99,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1609945386581-ec3f5d320e16?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.0,
    isDeleted: false,
  },
  {
    name: "Socks Multipack",
    description: "Comfortable cotton socks pack of 5.",
    price: 14.99,
    stock: 30,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "accessories",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  },

  // --------------------- SHOES (51–60) ---------------------
  {
    name: "SpeedRunner Sneakers",
    description: "Lightweight shoes built for speed and agility.",
    price: 69.99,
    stock: 8,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.3,
    isDeleted: false,
  },
  {
    name: "MountainHike Boots",
    description: "Sturdy boots designed for mountain trekking.",
    price: 120.49,
    stock: 5,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: true,
    ratings: 4.7,
    isDeleted: false,
  },
  {
    name: "CityWalk Loafers",
    description: "Casual loafers perfect for city strolls.",
    price: 55.75,
    stock: 10,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.0,
    isDeleted: false,
  },
  {
    name: "GymPro Trainers",
    description: "Shoes designed for gym and cross-training.",
    price: 64.99,
    stock: 7,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  },
  {
    name: "ComfyStep Sneakers",
    description: "Everyday sneakers with superior comfort.",
    price: 59.49,
    stock: 12,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.1,
    isDeleted: false,
  },
  {
    name: "NightRun Reflective Shoes",
    description: "Running shoes with reflective strip for night safety.",
    price: 72.99,
    stock: 6,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: true,
    ratings: 4.6,
    isDeleted: false,
  },
  {
    name: "EcoSneak Sneakers",
    description: "Eco-friendly sneakers made with recycled materials.",
    price: 68.5,
    stock: 8,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.3,
    isDeleted: false,
  },
  {
    name: "PowerStep Athletic Shoes",
    description: "High-performance shoes for athletes and runners.",
    price: 85.99,
    stock: 5,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: true,
    ratings: 4.7,
    isDeleted: false,
  },
  {
    name: "Classic Leather Sneakers",
    description: "Elegant leather sneakers for casual outings.",
    price: 79.49,
    stock: 6,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.5,
    isDeleted: false,
  },
  {
    name: "UrbanFlex Sneakers",
    description: "Modern sneakers with flexible sole for urban lifestyle.",
    price: 69.99,
    stock: 9,
    images: ["https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=60"],
    category: "shoes",
    featured: false,
    ratings: 4.2,
    isDeleted: false,
  }
];
